fix(ci): Allow concurrent modifications of PRs
# Issue

Dependabot PRs can contain both changes to the `.tool-versions`
file triggering the asdf2devbox workflow and changes to the
`go.mod`s triggering the package specs wokflow.

The slower workflow would fail with

```
[renovate/ginkgo-updates 13618e72b] 🤖🦾🛠️ go mod tidy & make
package-specs
 2 files changed, 4 insertions(+), 4 deletions(-)
To https://github.com/cloudfoundry/app-autoscaler-release
! [rejected]            renovate/ginkgo-updates ->
renovate/ginkgo-updates (fetch first)
error: failed to push some refs to
'https://github.com/cloudfoundry/app-autoscaler-release'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository
pushing
hint: to the same ref. You may want to first integrate the remote
changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for
details.
##[error]Process completed with exit code 1.
```

# Fix

Do a `git pull --rebase=true` before pushing.