Revert running `dependabot-auto-merge` in container
As it was causing the action source not to be found:

```
Error: Cannot find module '/home/runner/work/_actions/fastify/github-action-merge-dependabot/v3/dist/index.js'
```